"""
Generates the compose file for a cluster from the settings store.

Nobody hand-maintains ten near-identical service blocks. Pick your maps in the
UI, and this writes them - ports assigned in order from a base, one shared copy
of the server files, one shared config folder, and the first map acting as the
update master the others wait on.

The output is deliberately plain YAML with no anchors: it is meant to be read
and, if Obelisk is ever broken or stopped, run by hand with `docker compose up`.
"""

from . import maps as mapcat
from .settings import Store

HEADER = """# Generated by Obelisk - do not edit.
# Change settings in the admin page (or settings.json) and apply; this file is
# rewritten from scratch each time. It is plain YAML on purpose: if Obelisk is
# stopped or broken you can still run this cluster by hand with
#   docker compose -p {project} up -d
"""


def _q(v):
    """Quote a value for YAML, keeping numbers-as-strings intact."""
    s = "" if v is None else str(v)
    return '"%s"' % s.replace('\\', '\\\\').replace('"', '\\"')


def generate_compose(store, project="ark"):
    keys = store.get("maps")
    keys = [k.strip() for k in str(keys).split(",") if k.strip()] if isinstance(keys, str) else list(keys)
    chosen = mapcat.resolve(keys)
    if not chosen:
        raise ValueError("no maps selected - pick at least one")

    appdata   = store.get("appdata").rstrip("/")
    image     = store.get("ark_image")
    game_base = int(store.get("game_port_base"))
    rcon_base = int(store.get("rcon_port_base"))
    net       = "%s-net" % project
    master    = chosen[0]["key"]

    # label=host:port pairs so the manager can reach every map's RCON by name
    servers = ",".join("%s=asa_%s:%d" % (m["name"], m["key"], rcon_base + i)
                       for i, m in enumerate(chosen))

    L = [HEADER.format(project=project), "services:"]

    for i, m in enumerate(chosen):
        key, game_port, rcon_port = m["key"], game_base + i, rcon_base + i
        mem = store.get("mem_limit", key)
        L += [
            "  %s:" % key,
            "    image: %s" % image,
            "    container_name: asa_%s" % key,
            "    restart: unless-stopped",
            "    stop_grace_period: 210s",
            "    mem_limit: %s" % mem,
            "    networks: [%s]" % net,
            "    ulimits:",
            "      nofile: {soft: 1000000, hard: 1000000}",
        ]
        if key != master:
            # The master downloads ~30 GB of server files once; the rest wait for
            # it rather than nine containers fetching the same thing at once.
            L += ["    depends_on:", "      %s: {condition: service_healthy}" % master]
        L += [
            "    environment:",
            "      TZ: %s"                    % _q(store.get("timezone")),
            "      MAP_NAME: %s"              % _q(m["map_id"]),
            # POK keys the per-map instance folder off this, and coordinates updates
            # across the cluster with the role/priority pair: the master fetches the
            # new build, the followers wait their turn instead of ten containers
            # downloading the same 30 GB at once.
            "      INSTANCE_NAME: %s"         % _q(key),
            "      UPDATE_COORDINATION_ROLE: %s" % _q("MASTER" if key == master else "FOLLOWER"),
            "      UPDATE_COORDINATION_PRIORITY: %s" % _q(i + 1),
            "      SESSION_NAME: %s"          % _q(_session_name(store, i, m)),
            "      ASA_PORT: %s"              % _q(game_port),
            "      RCON_PORT: %s"             % _q(rcon_port),
            "      RCON_ENABLED: \"TRUE\"",
            "      SERVER_ADMIN_PASSWORD: %s" % _q(store.get("admin_password")),
            "      SERVER_PASSWORD: %s"       % _q(store.get("server_password")),
            "      MAX_PLAYERS: %s"           % _q(store.get("max_players")),
            "      CLUSTER_ID: %s"            % _q(store.get("cluster_id")),
            "      MOD_IDS: %s"               % _q(store.get("mod_ids")),
            "      PASSIVE_MODS: %s"          % _q(store.get("passive_mods")),
            "      CUSTOM_SERVER_ARGS: %s"    % _q(store.get("custom_server_args")),
            "      BATTLEEYE: %s"             % _q("TRUE" if store.get("battleye") else "FALSE"),
            # POK regenerates [MessageOfTheDay] from these on every start, so the
            # MOTD has to be set here and not in the shared INI.
            "      ENABLE_MOTD: %s"           % _q("TRUE" if store.get("motd_enabled") else "FALSE"),
            "      MOTD: %s"                  % _q(store.get("motd")),
            "      MOTD_DURATION: \"30\"",
            "      UPDATE_SERVER: \"TRUE\"",
            "      CHECK_FOR_UPDATE_INTERVAL: \"24\"",
            "      UPDATE_WINDOW_MINIMUM_TIME: %s" % _q(store.get("update_window_start")),
            "      UPDATE_WINDOW_MAXIMUM_TIME: %s" % _q(store.get("update_window_end")),
            "      RESTART_NOTICE_MINUTES: %s" % _q(store.get("restart_notice_minutes")),
            "      SAVE_WAIT_SECONDS: \"60\"",
            "      RANDOM_STARTUP_DELAY: \"TRUE\"",
            "      SHOW_ADMIN_COMMANDS_IN_CHAT: \"FALSE\"",
            "      DISPLAY_POK_MONITOR_MESSAGE: \"FALSE\"",
            "      CPU_OPTIMIZATION: \"FALSE\"",
            "      API: \"FALSE\"",
            # POK re-links Config/*.ini and SavedArks/<map> from here at every
            # start - this is what makes one shared settings file work for all maps.
            "      BACKUP_DIR: /home/pok/shared",
            "    ports:",
            '      - "%d:%d/udp"' % (game_port, game_port),
            '      - "%d:%d/tcp"' % (rcon_port, rcon_port),
            "    volumes:",
            '      - "%s/ServerFiles:/home/pok/arkserver"' % appdata,
            '      - "%s/Instance_%s/Saved:/home/pok/arkserver/ShooterGame/Saved"' % (appdata, key),
            '      - "%s/Cluster:/home/pok/arkserver/ShooterGame/Saved/clusters"' % appdata,
            '      - "%s/Shared:/home/pok/shared"' % appdata,
            "",
        ]

    # ---- the manager itself
    L += [
        "  obelisk:",
        "    image: %s" % store.get("obelisk_image"),
        "    container_name: obelisk",
        "    restart: unless-stopped",
        "    networks: [%s]" % net,
        "    environment:",
        "      TZ: %s"        % _q(store.get("timezone")),
        "      SERVERS: %s"   % _q(servers),
        "      RCON_PASSWORD: %s" % _q(store.get("admin_password")),
        "      DISCORD_TOKEN: %s" % _q(store.get("discord_token")),
        "      DISCORD_CHANNEL_ID: %s" % _q(store.get("discord_channel_id")),
        "      STATUS_PORT: %s" % _q(store.get("status_port")),
        "    ports:",
        '      - "%s:%s"' % (store.get("status_port"), store.get("status_port")),
        "    volumes:",
        '      - "%s/Obelisk:/data"' % appdata,
        '      - "%s/Shared:/home/pok/shared"' % appdata,
        "",
        "networks:",
        "  %s:" % net,
        "    name: %s" % net,
        "",
    ]
    return "\n".join(L)


def _session_name(store, index, m):
    """e.g. "MYCLUSTER 03 | Scorched Earth | PvE". Numbering keeps the cluster
    together alphabetically in the browser without a leading character that
    would stop it being listed at all."""
    bits = []
    prefix = str(store.get("session_prefix")).strip()
    if prefix:
        bits.append("%s %02d" % (prefix, index + 1))
    bits.append(m["name"])
    tags = str(store.get("session_tags")).strip()
    if tags:
        bits.append(tags)
    return " | ".join(bits)
