"""
Generates the compose file for a cluster from the settings store.

Nobody hand-maintains ten near-identical service blocks. Pick your maps in the
UI, and this writes them - ports assigned in order from a base, one shared copy
of the server files, one shared config folder, and the first map acting as the
update master the others wait on.

The output is deliberately plain YAML with no anchors: it is meant to be read
and, if Obelisk is ever broken or stopped, run by hand with `docker compose up`.
"""

from . import install, layout, naming
from . import maps as mapcat
from .plan import build_plan

HEADER = """# Generated by Obelisk - do not edit.
# Change settings in the admin page (or settings.json) and apply; this file is
# rewritten from scratch each time. It is plain YAML on purpose: if Obelisk is
# stopped or broken you can still run this cluster by hand with
#   docker compose -p {project} up -d
"""


def _q(v):
    """Quote a value for YAML, keeping numbers-as-strings intact."""
    s = "" if v is None else str(v)
    return '"%s"' % s.replace('\\', '\\\\').replace('"', '\\"')


def generate_compose(store, project="ark", in_use_ports=None):
    keys = store.get("maps")
    keys = [k.strip() for k in str(keys).split(",") if k.strip()] if isinstance(keys, str) else list(keys)
    chosen = mapcat.resolve(keys)
    if not chosen:
        raise ValueError("no maps selected - pick at least one")

    # One source of truth for ports and memory: if the plan won't boot, nothing is written.
    plan = build_plan(store, in_use_ports=in_use_ports)
    if not plan["ok"]:
        raise ValueError("can't generate this cluster: " + "; ".join(plan["problems"]))
    by_key = {r["map"]: r for r in plan["maps"]}
    ark       = str(store.get("appdata")).rstrip("/")     # host path of the Ark folder
    paths     = layout.ark_paths(ark)
    serverfiles = paths["serverfiles"]
    image     = store.get("ark_image")
    game_base = int(store.get("game_port_base"))
    rcon_base = int(store.get("rcon_port_base"))
    net       = "%s-net" % project
    master    = by_key[chosen[0]["key"]]["instance"]

    L = [HEADER.format(project=project), "services:"]

    for i, m in enumerate(chosen):
        key = m["key"]
        row = by_key[key]
        instance = row["instance"]
        game_port, rcon_port, mem = row["game_port"], row["rcon_port"], row["memory"]
        L += [
            "  %s:" % instance,
            "    image: %s" % image,
            "    container_name: %s" % naming.container_name(project, instance),
            "    restart: unless-stopped",
            "    stop_grace_period: 210s",
            "    mem_limit: %s" % mem,
            "    networks: [%s]" % net,
            "    ulimits:",
            "      nofile: {soft: 1000000, hard: 1000000}",
        ]
        if instance != master:
            # The master downloads ~30 GB of server files once; the rest wait for
            # it rather than nine containers fetching the same thing at once.
            L += ["    depends_on:", "      %s: {condition: service_healthy}" % master]
        L += [
            "    environment:",
            "      TZ: %s"                    % _q(store.get("timezone")),
            "      MAP_NAME: %s"              % _q(m["map_id"]),
            # POK keys the per-map instance folder off this, and coordinates updates
            # across the cluster with the role/priority pair: the master fetches the
            # new build, the followers wait their turn instead of ten containers
            # downloading the same 30 GB at once.
            "      INSTANCE_NAME: %s"         % _q(instance),
            "      UPDATE_COORDINATION_ROLE: %s" % _q("MASTER" if key == master else "FOLLOWER"),
            "      UPDATE_COORDINATION_PRIORITY: %s" % _q(i + 1),
            "      SESSION_NAME: %s"          % _q(_session_name(store, i, m)),
            "      ASA_PORT: %s"              % _q(game_port),
            "      RCON_PORT: %s"             % _q(rcon_port),
            "      RCON_ENABLED: \"TRUE\"",
            "      SERVER_ADMIN_PASSWORD: %s" % _q(store.get("admin_password")),
            "      SERVER_PASSWORD: %s"       % _q(store.get("server_password")),
            "      MAX_PLAYERS: %s"           % _q(store.get("max_players")),
            "      CLUSTER_ID: %s"            % _q(store.get("cluster_id")),
            "      MOD_IDS: %s"               % _q(store.get("mod_ids")),
            "      PASSIVE_MODS: %s"          % _q(store.get("passive_mods")),
            "      CUSTOM_SERVER_ARGS: %s"    % _q(store.get("custom_server_args")),
            "      BATTLEEYE: %s"             % _q("TRUE" if store.get("battleye") else "FALSE"),
            # POK regenerates [MessageOfTheDay] from these on every start, so the
            # MOTD has to be set here and not in the shared INI.
            "      ENABLE_MOTD: %s"           % _q("TRUE" if store.get("motd_enabled") else "FALSE"),
            "      MOTD: %s"                  % _q(store.get("motd")),
            "      MOTD_DURATION: \"30\"",
            "      UPDATE_SERVER: \"TRUE\"",
            "      CHECK_FOR_UPDATE_INTERVAL: \"24\"",
            "      UPDATE_WINDOW_MINIMUM_TIME: %s" % _q(store.get("update_window_start")),
            "      UPDATE_WINDOW_MAXIMUM_TIME: %s" % _q(store.get("update_window_end")),
            "      RESTART_NOTICE_MINUTES: %s" % _q(store.get("restart_notice_minutes")),
            "      SAVE_WAIT_SECONDS: \"60\"",
            "      RANDOM_STARTUP_DELAY: \"TRUE\"",
            "      SHOW_ADMIN_COMMANDS_IN_CHAT: \"FALSE\"",
            "      DISPLAY_POK_MONITOR_MESSAGE: \"FALSE\"",
            "      CPU_OPTIMIZATION: \"FALSE\"",
            "      API: \"FALSE\"",
            # POK re-links Config/*.ini and SavedArks/<map> from here at every
            # start - this is what makes one shared settings file work for all maps.
            "      BACKUP_DIR: /home/pok/shared",
            "    ports:",
            # The game port on both protocols. Gameplay is UDP, so direct connect works
            # either way - but the hand-built cluster this replaces publishes TCP too and
            # is demonstrably listed in the server browser, and matching something proven
            # beats reasoning about what the query path does or does not need.
            '      - "%d:%d/udp"' % (game_port, game_port),
            '      - "%d:%d/tcp"' % (game_port, game_port),
            '      - "%d:%d/tcp"' % (rcon_port, rcon_port),
            "    volumes:",
            # The game install sits outside the data root: 20+ GB that re-downloads,
            # and the one thing a portable backup must not carry.
            '      - "%s:/home/pok/arkserver"' % serverfiles,
            '      - "%s:/home/pok/arkserver/ShooterGame/Saved"' % layout.instance_dir(ark, instance),
            '      - "%s:/home/pok/arkserver/ShooterGame/Saved/clusters"' % paths["cluster"],
            '      - "%s:/home/pok/shared"' % paths["shared"],
            "",
        ]

    # ---- no manager service here, on purpose
    #
    # Obelisk manages this cluster; it is not part of it. It is installed once, by hand
    # or from the container template, and it creates, stops and relaunches the maps
    # above. Writing itself into the file it generates meant that launching from an
    # already-running Obelisk asked Docker to start a second one on the port the first
    # was already bound to: a collision with itself, every time, reported as an error
    # telling the operator to free a port that was already free.
    #
    # It also keeps the unit honest. This file is the cluster, so recreating it never
    # touches the thing doing the recreating.
    L += [
        "networks:",
        "  %s:" % net,
        "    name: %s" % net,
        "",
    ]

    return "\n".join(L)


def _session_name(store, index, m):
    """e.g. "MYCLUSTER 03 | Scorched Earth | PvE".

    Numbering keeps the cluster together alphabetically in the browser. Assembly and the
    63-character limit live in naming.py, because the limit applies to the finished
    string and not to any one field that goes into it.
    """
    return naming.assemble_session(store.get("session_prefix"), index, m["name"],
                                   store.get("session_tags"))

def _obelisk_host(store):
    """Host path of Obelisk's own data folder, for the stack it regenerates itself into.

    Asked of Docker like everything else. Falling back to the Ark folder's sibling keeps
    a generated file readable rather than empty if the socket cannot answer.
    """
    from . import install
    host, _how = install.host_path_of(install.container_root())
    if host:
        return host
    return str(store.get("appdata")).rstrip("/") + "-obelisk"
